version: '3'
services:
    Nginx:
        restart: 'unless-stopped'
        image: 'nginx'
        container_name: nginx
        ports:
            - "80:80"
            - "82:82"
            - "8080:8080"
        volumes:
            - '/root/workspace/WebServer/root:/usr/share/nginx/html:ro'
            - '/root/workspace/WebServer/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
            - '/etc/nginx/ssl/:/etc/nginx/ssl/:ro'
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - shrimp-net

    guard:
        build: ./nginx/guard
        container_name: guard
        restart: 'unless-stopped'
        volumes:
            - '/root/workspace/WebServer/nginx/guard/config.json:/app/config.json'
        networks:
            - shrimp-net

networks:
    shrimp-net:
        driver: bridge